apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-websocket-gateway
  labels:
    app: websocket-gateway
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: websocket
  selector:
    app: websocket-gateway
    release: {{ .Release.Name }}
